<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{4CA70DA0-75B9-4345-8D3E-2945F54577F0}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>SldWorksNodes</RootNamespace>
    <AssemblyName>SldWorksNodes</AssemblyName>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
    <NuGetPackageImportStamp>
    </NuGetPackageImportStamp>
    <XCadRegDll>false</XCadRegDll>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>..\bin\Debug\SolidWorks\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <DocumentationFile>..\bin\Debug\SolidWorks\SldWorksNodes.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>..\bin\Release\SolidWorks\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <DocumentationFile>..\bin\Release\SolidWorks\SldWorksNodes.xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="DynamoApplications">
      <HintPath>..\DynamoRuntime\DynamoApplications.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="DynamoCore">
      <HintPath>..\DynamoRuntime\DynamoCore.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="DynamoCoreWpf">
      <HintPath>..\DynamoRuntime\DynamoCoreWpf.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="DynamoServices">
      <HintPath>..\DynamoRuntime\DynamoServices.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Greg">
      <HintPath>..\DynamoRuntime\Greg.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Microsoft.VisualBasic">
      <Private>False</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
      <HintPath>..\packages\Newtonsoft.Json.8.0.3\lib\net45\Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PresentationCore">
      <Private>False</Private>
    </Reference>
    <Reference Include="PresentationFramework">
      <Private>False</Private>
    </Reference>
    <Reference Include="ProtoCore">
      <HintPath>..\DynamoRuntime\ProtoCore.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="ProtoGeometry, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\DynamoRuntime\ProtoGeometry.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SolidWorks.Interop.sldworks, Version=28.1.0.74, Culture=neutral, PublicKeyToken=7c4797c3e4eeac03, processorArchitecture=MSIL">
      <HintPath>..\packages\Xarial.XCad.SolidWorks.Interops.0.3.0\lib\net40\SolidWorks.Interop.sldworks.dll</HintPath>
      <EmbedInteropTypes>False</EmbedInteropTypes>
      <Private>False</Private>
    </Reference>
    <Reference Include="SolidWorks.Interop.swconst, Version=28.1.0.74, Culture=neutral, PublicKeyToken=19f43e188e4269d8, processorArchitecture=MSIL">
      <HintPath>..\packages\Xarial.XCad.SolidWorks.Interops.0.3.0\lib\net40\SolidWorks.Interop.swconst.dll</HintPath>
      <EmbedInteropTypes>False</EmbedInteropTypes>
      <Private>False</Private>
    </Reference>
    <Reference Include="SolidWorks.Interop.swpublished, Version=28.1.0.74, Culture=neutral, PublicKeyToken=89a97bdc5284e6d8, processorArchitecture=MSIL">
      <HintPath>..\packages\Xarial.XCad.SolidWorks.Interops.0.3.0\lib\net40\SolidWorks.Interop.swpublished.dll</HintPath>
      <EmbedInteropTypes>False</EmbedInteropTypes>
      <Private>False</Private>
    </Reference>
    <Reference Include="System">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
      <HintPath>..\packages\System.Buffers.4.5.1\lib\net461\System.Buffers.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Core">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Drawing">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
      <HintPath>..\packages\System.Memory.4.5.4\lib\net461\System.Memory.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Numerics">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Numerics.Vectors, Version=4.1.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>..\packages\System.Numerics.Vectors.4.5.0\lib\net46\System.Numerics.Vectors.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Resources.Extensions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
      <HintPath>..\packages\System.Resources.Extensions.7.0.0-preview.1.22076.8\lib\net462\System.Resources.Extensions.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>..\packages\System.Runtime.CompilerServices.Unsafe.4.5.3\lib\net461\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\Prism.4.1.0.0\lib\NET40\System.Windows.Interactivity.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Xaml">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Xml.Linq">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Data.DataSetExtensions">
      <Private>False</Private>
    </Reference>
    <Reference Include="Microsoft.CSharp">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Data">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Net.Http">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Xml">
      <Private>False</Private>
    </Reference>
    <Reference Include="WindowsBase">
      <Private>False</Private>
    </Reference>
    <Reference Include="WindowsFormsIntegration" />
    <Reference Include="Xarial.XCad, Version=0.7.12.0, Culture=neutral, PublicKeyToken=60dcaf351d4060db, processorArchitecture=MSIL">
      <HintPath>..\packages\Xarial.XCad.0.7.12\lib\net461\Xarial.XCad.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Xarial.XCad.SolidWorks, Version=0.7.12.0, Culture=neutral, PublicKeyToken=60dcaf351d4060db, processorArchitecture=MSIL">
      <HintPath>..\packages\Xarial.XCad.SolidWorks.0.7.12\lib\net461\Xarial.XCad.SolidWorks.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Xarial.XCad.Toolkit, Version=0.7.12.0, Culture=neutral, PublicKeyToken=60dcaf351d4060db, processorArchitecture=MSIL">
      <HintPath>..\packages\Xarial.XCad.Toolkit.0.7.12\lib\net461\Xarial.XCad.Toolkit.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Assembly\Component.cs" />
    <Compile Include="Base\BrepNode.cs" />
    <Compile Include="Base\SwNode.cs" />
    <Compile Include="Base\SwNodeModel.cs" />
    <Compile Include="Brep\Edge.cs" />
    <Compile Include="Brep\Face.cs" />
    <Compile Include="Brep\Loop.cs" />
    <Compile Include="Brep\Vertex.cs" />
    <Compile Include="ConfigurationManager\SwConfiguration.cs" />
    <Compile Include="ConfigurationManager\ConfigurationManager.cs" />
    <Compile Include="CustomProperty\CustomProperty.cs" />
    <Compile Include="CustomProperty\CustomPropertyCreation.cs" />
    <Compile Include="CustomProperty\CustomPropertyManager.cs" />
    <Compile Include="CustomProperty\StringCustomProperty.cs" />
    <Compile Include="Dimension\Dimension.cs" />
    <Compile Include="Document\AssemblyDocument.cs" />
    <Compile Include="Document\Document.cs" />
    <Compile Include="Document\DrawingDocument.cs" />
    <Compile Include="Document\PartDocument.cs" />
    <Compile Include="EquationMgr\Equation.cs" />
    <Compile Include="Extension\FeatTypeNameUtil.cs" />
    <Compile Include="Extension\IFeatureExtension.cs" />
    <Compile Include="Extension\IModelDoc2Extension.cs" />
    <Compile Include="Extension\ISldWorksExtension.cs" />
    <Compile Include="Feature\Base\SpecFeature.cs" />
    <Compile Include="Feature\ExtrudeFeature.cs" />
    <Compile Include="Feature\Feature.cs" />
    <Compile Include="Feature\RefPlane.cs" />
    <Compile Include="GeometryExtension\Line2D.cs" />
    <Compile Include="GeometryExtension\Line3D.cs" />
    <Compile Include="GeometryExtension\Point3DExtension.cs" />
    <Compile Include="GeometryExtension\PointDirection.cs" />
    <Compile Include="GeometryExtension\PointExtension.cs" />
    <Compile Include="GeometryExtension\Rect3DExtension.cs" />
    <Compile Include="GeometryExtension\RectExtensin.cs" />
    <Compile Include="GeometryExtension\RectPoint3Ds.cs" />
    <Compile Include="GeometryExtension\RectPoints.cs" />
    <Compile Include="GeometryExtension\Transform3DExtension.cs" />
    <Compile Include="GeometryExtension\Vector3DExtenions.cs" />
    <Compile Include="GeometryExtension\Vector4Extension.cs" />
    <Compile Include="GeometryExtension\VectorExtension.cs" />
    <Compile Include="Geometry\Cone.cs" />
    <Compile Include="Geometry\Curve.cs" />
    <Compile Include="Geometry\Curve\Arc3D.cs" />
    <Compile Include="Geometry\Body.cs" />
    <Compile Include="Geometry\BodyBoolOperation.cs" />
    <Compile Include="Geometry\Curve\Circle3D.cs" />
    <Compile Include="Geometry\Cube.cs" />
    <Compile Include="Geometry\Curve\Ellipse.cs" />
    <Compile Include="Geometry\Curve\Line3D.cs" />
    <Compile Include="Geometry\Curve\Point3D.cs" />
    <Compile Include="Geometry\Base\SheetBody.cs" />
    <Compile Include="Geometry\Base\SurfaceBody.cs" />
    <Compile Include="Geometry\Base\SwBodyNode.cs" />
    <Compile Include="Geometry\Base\SwCurveBodyNode.cs" />
    <Compile Include="Geometry\Curve\Vector3D.cs" />
    <Compile Include="Geometry\Cylinder.cs" />
    <Compile Include="Manager\UnitManager.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Sketch\Sketch.cs" />
    <Compile Include="SldViewExtension.cs" />
    <Compile Include="SwException\ActiveDocIsNotPartDocException.cs" />
    <Compile Include="SwException\ActiveDocNotFoundException.cs" />
    <Compile Include="SwException\BodyOperationErrorException.cs" />
    <Compile Include="SwException\CustomPropertyAddException.cs" />
    <Compile Include="SwException\FeatureNotFoundException.cs" />
    <Compile Include="SwException\FeatureTypeNameErrorException.cs" />
    <Compile Include="SwException\PIDErrorException.cs" />
    <Compile Include="SwException\SelectionNotFoundException.cs" />
    <Compile Include="SwException\SelectionTypeErrorException.cs" />
    <Compile Include="SwException\SwObjectLostException.cs" />
    <Compile Include="Transform\Transform.cs" />
    <Compile Include="Util\BodyBuilder.cs" />
    <Compile Include="Util\CurveBuilder.cs" />
    <Compile Include="Util\DispathWrapperUtil.cs" />
    <Compile Include="Util\SwContextUtil.cs" />
    <Compile Include="Util\PIDUtil.cs" />
    <Compile Include="Manager\SldContextManager.cs" />
    <Compile Include="View\SolidWorksInfoWindow.xaml.cs">
      <DependentUpon>SolidWorksInfoWindow.xaml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Icons\solidworks.png" />
    <None Include="Resources\Dimension.png" />
    <None Include="SldWorksNodes.Migrations.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="SldWorksNodes_DynamoCustomization.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Include="app.config" />
    <None Include="packages.config" />
    <None Include="pkg.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Selection\" />
    <Folder Include="Solid\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SldWorksService\SldWorksService.csproj">
      <Project>{f6fb5acd-b3c3-4186-acfa-8a6502e1f26d}</Project>
      <Name>SldWorksService</Name>
      <Private>False</Private>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Page Include="View\SolidWorksInfoWindow.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <Import Project="..\packages\Xarial.XCad.SolidWorks.0.7.12\build\Xarial.XCad.SolidWorks.targets" Condition="Exists('..\packages\Xarial.XCad.SolidWorks.0.7.12\build\Xarial.XCad.SolidWorks.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>这台计算机上缺少此项目引用的 NuGet 程序包。使用“NuGet 程序包还原”可下载这些程序包。有关更多信息，请参见 http://go.microsoft.com/fwlink/?LinkID=322105。缺少的文件是 {0}。</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\Xarial.XCad.SolidWorks.0.7.12\build\Xarial.XCad.SolidWorks.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Xarial.XCad.SolidWorks.0.7.12\build\Xarial.XCad.SolidWorks.targets'))" />
  </Target>
</Project>